variables:
    GIT_SUBMODULE_STRATEGY: recursive

build:
    stage: build
    artifacts:
        paths:
            - build/*
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make -j${NUM_JOBS:-$(nproc)}

test:
    stage: test
    script:
        - cd build
        - make test
